// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7kV_eV9-cy1wppQCrlPDUR7Va-6BlAxw',
    appId: '1:740312507494:web:d4ca2ea441d760438479a7',
    messagingSenderId: '740312507494',
    projectId: 'flrebase-series',
    authDomain: 'flrebase-series.firebaseapp.com',
    storageBucket: 'flrebase-series.firebasestorage.app',
    measurementId: 'G-GDMGGWRS8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gKU1ZeG2sr-bEEJ3rUEjtKrR0MXDow4',
    appId: '1:740312507494:android:be28d53ba846072e8479a7',
    messagingSenderId: '740312507494',
    projectId: 'flrebase-series',
    storageBucket: 'flrebase-series.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF-E1hpo199l4ltlsXq6gEcoL2KvTRGok',
    appId: '1:740312507494:ios:54d2cf48461f31868479a7',
    messagingSenderId: '740312507494',
    projectId: 'flrebase-series',
    storageBucket: 'flrebase-series.firebasestorage.app',
    iosBundleId: 'com.example.firebaseWscube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF-E1hpo199l4ltlsXq6gEcoL2KvTRGok',
    appId: '1:740312507494:ios:54d2cf48461f31868479a7',
    messagingSenderId: '740312507494',
    projectId: 'flrebase-series',
    storageBucket: 'flrebase-series.firebasestorage.app',
    iosBundleId: 'com.example.firebaseWscube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7kV_eV9-cy1wppQCrlPDUR7Va-6BlAxw',
    appId: '1:740312507494:web:9a730edc3310b17c8479a7',
    messagingSenderId: '740312507494',
    projectId: 'flrebase-series',
    authDomain: 'flrebase-series.firebaseapp.com',
    storageBucket: 'flrebase-series.firebasestorage.app',
    measurementId: 'G-87P6LG3XDC',
  );
}
